import { User, Wallet, Counter, LedgerTransaction, NotificationItem, ReferralTreeData } from './types';

// Anchor timestamp (current epoch)
const now = Date.now();
const DAY_MS = 24 * 60 * 60 * 1000;

export const mockCurrentUser: User = {
  id: 'usr_89214',
  name: 'Alex Vance',
  email: 'alex.vance@cloudnode.network',
  referralCode: 'CLOUD-X892',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&q=80',
  joinedDate: '2026-01-15',
  tier: 'Node Validator Alpha',
};

export const mockWallet: Wallet = {
  availableBalance: 142.50,
  rewardBoxBalance: 38.75, // Referral reward box ready to claim
  currency: 'USDT',
  totalWithdrawn: 120.00,
  totalEarned: 301.25,
};

export const mockCounters: Counter[] = [
  {
    id: 'cnt_alpha_01',
    name: 'Stratus Alpha Tier-1',
    price: 15.00,
    dailyReward: 0.50,
    durationDays: 60,
    createdAt: now - 18 * DAY_MS,
    expiresAt: now + 42 * DAY_MS,
    cycleStartedAt: now - 18 * DAY_MS,
    status: 'running',
    completedCycles: 18,
    hashRate: '12.4 GH/s',
    efficiency: 99.4,
  },
  {
    id: 'cnt_nimbus_02',
    name: 'Nimbus Core Turbo',
    price: 45.00,
    dailyReward: 1.65,
    durationDays: 60,
    createdAt: now - 6 * DAY_MS,
    expiresAt: now + 54 * DAY_MS,
    cycleStartedAt: now - 6 * DAY_MS,
    status: 'running',
    completedCycles: 6,
    hashRate: '42.8 GH/s',
    efficiency: 99.8,
  },
  {
    id: 'cnt_cumulus_03',
    name: 'Cumulus Pro Unit',
    price: 30.00,
    dailyReward: 1.10,
    durationDays: 60,
    createdAt: now - 1 * DAY_MS,
    expiresAt: now + 59 * DAY_MS,
    cycleStartedAt: null,
    status: 'waiting_activation',
    completedCycles: 0,
    hashRate: '25.0 GH/s',
    efficiency: 100.0,
  },
  {
    id: 'cnt_titan_04',
    name: 'Cirrus Starter Pod',
    price: 15.00,
    dailyReward: 0.50,
    durationDays: 60,
    createdAt: now - 72 * DAY_MS,
    expiresAt: now - 12 * DAY_MS,
    cycleStartedAt: now - 72 * DAY_MS,
    status: 'expired',
    completedCycles: 60,
    hashRate: '12.0 GH/s',
    efficiency: 98.2,
  },
];

export const mockLedger: LedgerTransaction[] = [
  {
    id: 'tx_9012',
    type: 'daily_reward',
    amount: 2.15,
    date: now - 2 * 60 * 60 * 1000, // 2 hours ago
    status: 'completed',
    description: 'Daily counter output payout (2 active nodes)',
    referenceId: 'cnt_alpha_01, cnt_nimbus_02',
  },
  {
    id: 'tx_9011',
    type: 'referral_bonus',
    amount: 14.50,
    date: now - 14 * 60 * 60 * 1000, // 14 hours ago
    status: 'completed',
    description: 'Tier-1 referral commission (user: @crypto_dave)',
    referenceId: 'ref_8829',
  },
  {
    id: 'tx_9010',
    type: 'counter_purchase',
    amount: -30.00,
    date: now - 24 * 60 * 60 * 1000, // 1 day ago
    status: 'completed',
    description: 'Purchased Cumulus Pro Unit (Awaiting cycle activation)',
    referenceId: 'cnt_cumulus_03',
  },
  {
    id: 'tx_9009',
    type: 'daily_reward',
    amount: 2.15,
    date: now - 26 * 60 * 60 * 1000,
    status: 'completed',
    description: 'Daily counter output payout (2 active nodes)',
    referenceId: 'cnt_alpha_01, cnt_nimbus_02',
  },
  {
    id: 'tx_9008',
    type: 'withdrawal',
    amount: -60.00,
    date: now - 3 * DAY_MS,
    status: 'completed',
    description: 'USDT withdrawal to TRC-20 wallet (TXYZ...99a)',
    referenceId: 'wd_44102',
  },
  {
    id: 'tx_9007',
    type: 'deposit',
    amount: 100.00,
    date: now - 7 * DAY_MS,
    status: 'completed',
    description: 'USDT external top-up via Polygon Network',
    referenceId: 'dep_1092',
  },
];

export const mockNotifications: NotificationItem[] = [
  {
    id: 'notif_1',
    title: 'Daily Rewards Credited',
    message: '+2.15 USDT has been added to your available balance from active counters.',
    timestamp: now - 2 * 60 * 60 * 1000,
    read: false,
    type: 'reward',
  },
  {
    id: 'notif_2',
    title: 'Counter Ready to Activate',
    message: 'Cumulus Pro Unit is waiting for initial cycle activation.',
    timestamp: now - 24 * 60 * 60 * 1000,
    read: false,
    type: 'cycle',
  },
  {
    id: 'notif_3',
    title: 'Referral Reward Received',
    message: 'Your direct referee joined with code CLOUD-X892. +14.50 USDT in Reward Box.',
    timestamp: now - 14 * 60 * 60 * 1000,
    read: true,
    type: 'referral',
  },
];

export const mockReferrals: ReferralTreeData = {
  level1: [
    {
      id: 'ref_l1_01',
      name: 'Dave Miller',
      username: '@crypto_dave',
      level: 1,
      joinedAt: now - 28 * DAY_MS,
      activeCounters: 3,
      totalVolume: 90.00,
      commissionEarned: 18.50,
      status: 'active',
    },
    {
      id: 'ref_l1_02',
      name: 'Sarah Chen',
      username: '@sarah_node',
      level: 1,
      joinedAt: now - 19 * DAY_MS,
      activeCounters: 2,
      totalVolume: 60.00,
      commissionEarned: 12.25,
      status: 'active',
    },
    {
      id: 'ref_l1_03',
      name: 'Elena Rostova',
      username: '@elena_val',
      level: 1,
      joinedAt: now - 8 * DAY_MS,
      activeCounters: 1,
      totalVolume: 30.00,
      commissionEarned: 5.00,
      status: 'active',
    },
    {
      id: 'ref_l1_04',
      name: 'Tom Reynolds',
      username: '@tom_cloud',
      level: 1,
      joinedAt: now - 3 * DAY_MS,
      activeCounters: 1,
      totalVolume: 15.00,
      commissionEarned: 3.00,
      status: 'active',
    },
  ],
  level2: [
    {
      id: 'ref_l2_01',
      name: 'Marcus Klein',
      username: '@marcus_k',
      level: 2,
      parentId: 'ref_l1_01',
      joinedAt: now - 20 * DAY_MS,
      activeCounters: 2,
      totalVolume: 60.00,
      commissionEarned: 3.00,
      status: 'active',
    },
    {
      id: 'ref_l2_02',
      name: 'Lucas Brown',
      username: '@lucas_b',
      level: 2,
      parentId: 'ref_l1_01',
      joinedAt: now - 15 * DAY_MS,
      activeCounters: 2,
      totalVolume: 45.00,
      commissionEarned: 2.25,
      status: 'active',
    },
    {
      id: 'ref_l2_03',
      name: 'Kenji Sato',
      username: '@kenji_s',
      level: 2,
      parentId: 'ref_l1_02',
      joinedAt: now - 12 * DAY_MS,
      activeCounters: 1,
      totalVolume: 15.00,
      commissionEarned: 1.15,
      status: 'active',
    },
    {
      id: 'ref_l2_04',
      name: 'Chloe Dubois',
      username: '@chloe_d',
      level: 2,
      parentId: 'ref_l1_03',
      joinedAt: now - 6 * DAY_MS,
      activeCounters: 1,
      totalVolume: 30.00,
      commissionEarned: 1.50,
      status: 'active',
    },
  ],
  level3: [
    {
      id: 'ref_l3_01',
      name: 'Zack Taylor',
      username: '@zack_web3',
      level: 3,
      parentId: 'ref_l2_01',
      joinedAt: now - 14 * DAY_MS,
      activeCounters: 1,
      totalVolume: 30.00,
      commissionEarned: 0.60,
      status: 'active',
    },
    {
      id: 'ref_l3_02',
      name: 'Priya Menon',
      username: '@priya_m',
      level: 3,
      parentId: 'ref_l2_03',
      joinedAt: now - 9 * DAY_MS,
      activeCounters: 1,
      totalVolume: 15.00,
      commissionEarned: 0.30,
      status: 'active',
    },
    {
      id: 'ref_l3_03',
      name: 'Liam Wilson',
      username: '@liam_w',
      level: 3,
      parentId: 'ref_l2_02',
      joinedAt: now - 4 * DAY_MS,
      activeCounters: 1,
      totalVolume: 15.00,
      commissionEarned: 0.30,
      status: 'active',
    },
  ],
};

